### ISSUE TITLE
Compiling for TensorRT 7.1.3.4 with CUDA 10.2

### ISSUE THREAD

**Issue by Darshcg** [NVIDIA/trt-samples-for-hackathon-cn#1]
Hi,

Thanks for your Good work.

I want to build the same in my local machine which has TensorRT 7.1.3.4 with CUDA 10.2.
But when I am running I am facing issues.
Where do I need to change in order to make it work for TensorRT 7.1.3.4 with CUDA 10.2?

Thanks,
Darshan C G

**Comment by 13281306705** [comment]
Have you solved this problem? I'm in the same trouble

**Comment by shining365** [comment]
Due to our limited personal, we only maintain our code against latest TRT. You may find useful samples in the TRT package. Sorry for the inconvenience.
