### ISSUE TITLE
cookbook/02-API/Layer中Einsum文档错误

### ISSUE THREAD

**Issue by gasSolid** [NVIDIA/trt-samples-for-hackathon-cn#13]
在Einsum层作点积运算示例中，求和运算应该是0.0 * 1.0 + 1.0 * 1.0 + 2.0 * 1.0 + 3.0 * 1.0 = 6.0

**Comment by wili-65535** [comment]
2.0 写成 0.2 了Orz
已修正，感谢感谢！
