### ISSUE TITLE
How to use the scatterND plugin?

### ISSUE THREAD

**Issue by rsj007** [NVIDIA/trt-samples-for-hackathon-cn#2]
Hi! I want to convert a onnx model to tensorrt. However the error is scatterND is not supported by tensorrt. How can I impletment this custom plugin? Thanks a lot.

**Comment by 13281306705** [comment]
Is it convenient for you to leave a contact information? I'd like to talk to you about how to use alphpose_ TRT, thank you very much.My email is 1317594600@qq.com

**Comment by shining365** [comment]
You can find scatterND here: https://github.com/NVIDIA/trt-samples-for-hackathon-cn/blob/master/plugins/ScatterND.h
You can run it by https://github.com/NVIDIA/trt-samples-for-hackathon-cn/blob/master/python/app_ScatterND_plugin.py

You may refer to this sample to see how ONNX nodes can be replaced by a plugin: https://github.com/NVIDIA/trt-samples-for-hackathon-cn/tree/master/cookbook/06-PluginAndParser/pyTorch-LayerNorm
Or this one
https://github.com/NVIDIA/trt-samples-for-hackathon-cn/blob/master/python/app_onnx_custom.py
