### ISSUE TITLE
Convert3DMMTo2DMM例子中 reshape维度问题？

### ISSUE THREAD

**Issue by BaofengZan** [NVIDIA/trt-samples-for-hackathon-cn#25]
https://github.com/NVIDIA/trt-samples-for-hackathon-cn/blob/32bb0afc33241f4553c643656fbf65290c0bc4db/cookbook/10-BestPractice/Convert3DMMTo2DMM/main.py#L128
这里输入的是B\*T\*1的tensor，不应该reshape成(B*T)*1吗？ 为什么reshape成了256？

**Comment by wili-65535** [comment]
感谢纠错！这个地方确实应该是 1 而不是 256。同理第 122 行 bTComma1Tensor 的形状也应该是 [2] 而不是 [1]。

不过，由于 TRT 在构建期会重新计算所有层的形状和数据类型，所以这里手工写进去的 256 会被 TRT 忽略掉，对构建没有影响。

**Comment by BaofengZan** [comment]
好的。感谢回答
