### ISSUE TITLE
ReducePlugin编译错误！！！

### ISSUE THREAD

**Issue by DataXujing** [NVIDIA/trt-samples-for-hackathon-cn#30]
<https://github.com/NVIDIA/trt-samples-for-hackathon-cn/tree/master/cookbook/05-Plugin/PluginReposity/ReducePlugin>在编译的时候报如下错误：
我们用的环境是：<https://github.com/NVIDIA/trt-samples-for-hackathon-cn/blob/master/hackathon/setup.md>
![2022-06-15_123106](https://user-images.githubusercontent.com/24708267/173737204-ab5d6383-2c43-41c5-a96b-e2e1af5d2289.png)

**Comment by wili-65535** [comment]
这一版本的 ReducePlugin 应该是 TRT6 或者 TRT7 时写的，在更新的 TRT8 中，相关 class 成员函数的可访问性和修饰符发生了变化，不能直接编译。

这个问题以后 cookbook 中会慢慢修复，感谢你提出这个问题；如果急需使用这个 plugin 的话可以参考 05-Plugin/usePluginV2DynamicExt 的例子进行修改。
