### ISSUE TITLE
where is the batchedNMSIO.npz?

### ISSUE THREAD

**Issue by GeneralJing** [NVIDIA/trt-samples-for-hackathon-cn#44]
i want to learn the plugin content, but i cannot find the batchedNMSIO.npz. can anyone supply it?

**Comment by wili-65535** [comment]
I restore the IO data in https://github.com/NVIDIA/trt-samples-for-hackathon-cn/tree/master/cookbook/05-Plugin/PluginReposity/BatchedNMS_TRTPlugin-TRT8 now.

Thank you for raising the issue.

**Comment by GeneralJing** [comment]
thank you. That helps a lot.
