### ISSUE TITLE
关于09-advance里面的multiSteam，关于run2函数，如何传入data数据进行推理？

### ISSUE THREAD

**Issue by mingwz** [NVIDIA/trt-samples-for-hackathon-cn#51]

**Comment by wili-65535** [comment]
I'm sorry for remaining this problem in the sample code Orz.

You can refer to the sample code in 09-Advance/StreamAndAsync to solve this problem (I will fix it in the same way later).

In general, we need to take out the pointer of the allocated page-locked memory buffer, pack it into a numpy array, and then use this numpy arrays to write and read the data in Python.

**Comment by mingwz** [comment]
感谢大佬的提醒，我悟了 @wili-65535
