### ISSUE TITLE
same code in '李玮' demo

### ISSUE THREAD

**Issue by pandaGst** [NVIDIA/trt-samples-for-hackathon-cn#7]
https://github.com/NVIDIA/trt-samples-for-hackathon-cn/blob/master/hackathon/%E6%9D%8E%E7%8E%AEAPI%E6%90%AD%E5%BB%BA%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/Loop%E5%AE%9E%E7%8E%B0%E5%8D%95%E5%B1%82%E5%8D%95%E5%90%91LSTM.py and https://github.com/NVIDIA/trt-samples-for-hackathon-cn/blob/master/hackathon/%E6%9D%8E%E7%8E%AEAPI%E6%90%AD%E5%BB%BA%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/Loop%E5%AE%9E%E7%8E%B0%E5%8D%95%E5%B1%82%E5%8F%8C%E5%90%91LSTM.py seems the same file. Is there a mistake at oploading?

**Comment by shining365** [comment]
Thanks for pointing out this error. New code can be found in https://github.com/NVIDIA/trt-samples-for-hackathon-cn/blob/master/cookbook/02-API/Layer/Loop%E7%BB%93%E6%9E%84%E5%AE%9E%E7%8E%B0RNN.md
