### ISSUE TITLE
07-Tool/trtexec/command.sh fail

### ISSUE THREAD

**Issue by bolin12** [NVIDIA/trt-samples-for-hackathon-cn#99]
07-Tool/trtexec/result-03.log：

&&&& RUNNING TensorRT.trtexec [TensorRT v8601] # trtexec model-02.plan --trt --shapes=tensorX:4x1x28x28 --noDataTransfers --useSpinWait --useCudaGraph --verbose
[11/27/2023-08:17:03] [E] Model missing or format not recognized

**Comment by wanderHZ** [comment]
You can change the code in the command.sh to the following format:
```
# 03-Load TensorRT engine built above and do inference
trtexec \
    --loadEngine=model-02.plan \
    --shapes=tensorX:4x1x28x28 \
    --noDataTransfers \
    --useSpinWait \
    --useCudaGraph \
    --verbose \
    > result-03.log 2>&1
```
